jobs:
    - script: >
        multibranchPipelineJob('jenkins-as-code') {
          branchSources {
            github {
              // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
              id('12312313') // IMPORTANT: use a constant and unique identifier
              scanCredentialsId('github')
              repoOwner('psacc')
              repository('jenkins-as-code')
            }
          }
          orphanedItemStrategy {
            discardOldItems {
              numToKeep(1)
            }
          }
          triggers {
            periodic(5)
          }
        }